// Code generated by generate_tokens.go

package token

type Type int

const (
	Invalid Type = iota
	Identifier
	Integer
	String
	Const
	Func
	Let
	Plus
)

func (t Type) String() string {
	if t < 0 || t > Plus {
		t = Invalid
	}
	return names[t]
}

var names = []string{"<invalid>", "<identifier>", "<integer>", "<string>", "const", "func", "let", "+"}

type TrieNode struct {
	Rune     rune
	Type     Type
	Children []*TrieNode
}

var Fixed = &TrieNode{'\x00', Invalid, []*TrieNode{{'+', Plus, nil}, {'c', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'s', Invalid, []*TrieNode{{'t', Const, nil}}}}}}}}}, {'f', Invalid, []*TrieNode{{'u', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'c', Func, nil}}}}}}}, {'l', Invalid, []*TrieNode{{'e', Invalid, []*TrieNode{{'t', Let, nil}}}}}}}
