// Code generated by generate_tokens.go

package token

type Type int

const (
	Invalid Type = iota
	Comment
	Identifier
	Integer
	String
	Const
	Enum
	Export
	ForSome
	Func
	If
	Impl
	Let
	Return
	Struct
	Trait
	Union
	Assign
	Asterisk
	Bang
	CloseBrace
	CloseBracket
	CloseParen
	Colon
	Comma
	Dot
	Ellipses
	Less
	Minus
	OpenBrace
	OpenBracket
	OpenParen
	Plus
	Semicolon
)

func (t Type) String() string {
	if t < 0 || t > Semicolon {
		t = Invalid
	}
	return names[t]
}
func (t Type) GoString() string {
	if t < 0 || t > Semicolon {
		t = Invalid
	}
	return goNames[t]
}

var names = []string{"<invalid>", "<comment>", "<identifier>", "<integer>", "<string>", "const", "enum", "export", "forSome", "func", "if", "impl", "let", "return", "struct", "trait", "union", "=", "*", "!", "}", "]", ")", ":", ",", ".", "...", "<", "-", "{", "[", "(", "+", ";"}
var goNames = []string{"token.Invalid", "token.Comment", "token.Identifier", "token.Integer", "token.String", "token.Const", "token.Enum", "token.Export", "token.ForSome", "token.Func", "token.If", "token.Impl", "token.Let", "token.Return", "token.Struct", "token.Trait", "token.Union", "token.Assign", "token.Asterisk", "token.Bang", "token.CloseBrace", "token.CloseBracket", "token.CloseParen", "token.Colon", "token.Comma", "token.Dot", "token.Ellipses", "token.Less", "token.Minus", "token.OpenBrace", "token.OpenBracket", "token.OpenParen", "token.Plus", "token.Semicolon"}

type TrieNode struct {
	Rune     rune
	Type     Type
	Children []*TrieNode
}

var Fixed = &TrieNode{'\x00', Invalid, []*TrieNode{{'!', Bang, nil}, {'(', OpenParen, nil}, {')', CloseParen, nil}, {'*', Asterisk, nil}, {'+', Plus, nil}, {',', Comma, nil}, {'-', Minus, nil}, {'.', Dot, []*TrieNode{{'.', Invalid, []*TrieNode{{'.', Ellipses, nil}}}}}, {':', Colon, nil}, {';', Semicolon, nil}, {'<', Less, nil}, {'=', Assign, nil}, {'[', OpenBracket, nil}, {']', CloseBracket, nil}, {'c', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'s', Invalid, []*TrieNode{{'t', Const, nil}}}}}}}}}, {'e', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'u', Invalid, []*TrieNode{{'m', Enum, nil}}}}}, {'x', Invalid, []*TrieNode{{'p', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'r', Invalid, []*TrieNode{{'t', Export, nil}}}}}}}}}}}, {'f', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'r', Invalid, []*TrieNode{{'S', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'m', Invalid, []*TrieNode{{'e', ForSome, nil}}}}}}}}}}}, {'u', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'c', Func, nil}}}}}}}, {'i', Invalid, []*TrieNode{{'f', If, nil}, {'m', Invalid, []*TrieNode{{'p', Invalid, []*TrieNode{{'l', Impl, nil}}}}}}}, {'l', Invalid, []*TrieNode{{'e', Invalid, []*TrieNode{{'t', Let, nil}}}}}, {'r', Invalid, []*TrieNode{{'e', Invalid, []*TrieNode{{'t', Invalid, []*TrieNode{{'u', Invalid, []*TrieNode{{'r', Invalid, []*TrieNode{{'n', Return, nil}}}}}}}}}}}, {'s', Invalid, []*TrieNode{{'t', Invalid, []*TrieNode{{'r', Invalid, []*TrieNode{{'u', Invalid, []*TrieNode{{'c', Invalid, []*TrieNode{{'t', Struct, nil}}}}}}}}}}}, {'t', Invalid, []*TrieNode{{'r', Invalid, []*TrieNode{{'a', Invalid, []*TrieNode{{'i', Invalid, []*TrieNode{{'t', Trait, nil}}}}}}}}}, {'u', Invalid, []*TrieNode{{'n', Invalid, []*TrieNode{{'i', Invalid, []*TrieNode{{'o', Invalid, []*TrieNode{{'n', Union, nil}}}}}}}}}, {'{', OpenBrace, nil}, {'}', CloseBrace, nil}}}
